apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev

resources:
- namespace.yaml
- ../base

patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: adaltas/adaltasdemocicd
  newTag: 5597da9d84baa9b723a64f15de64bb393a1cc0d3
