apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod

resources:
- namespace.yaml
- ../base

patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: adaltas/adaltasdemocicd
  newTag: ff9b048629848bfd7471bacacd1ba68a0f855943
